<?xml version="1.0"?>
<robot name="lab" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="base_height" value="1.0"/>
  <xacro:property name="tube_height" value="0.1030"/>
  <xacro:property name="x_tube" value="0.3"/>
  <xacro:property name="y_tube1" value="0"/>
  <xacro:property name="y_tube2" value="0.3"/>
  <xacro:property name="y_tube3" value="0.6"/>

  <!-- Include Yumi with table -->
  <!-- <xacro:include filename="$(find yumi_description)/urdf/yumi.urdf.xacro"/> -->

  <!-- Include test tubes -->
  <xacro:include filename="$(find YumiProjectThesis)/urdf/test_tube/test_tube.urdf.xacro"/>
  <xacro:test_tube_urdf prefix="test_tube_1_"/>
  <xacro:test_tube_urdf prefix="test_tube_2_"/>
  <xacro:test_tube_urdf prefix="test_tube_3_"/>

  <link name="base"/>
  <!-- Joint test_tubes -->
  <joint name="test_tube_1_joint" type="floating">
    <parent link="base"/>
    <child link="test_tube_1_tube_link"/>
    <origin xyz="${x_tube} ${y_tube1} ${(base_height+tube_height)}"/>
  </joint>

  <joint name="test_tube_2_joint" type="floating">
    <parent link="base"/>
    <child link="test_tube_2_tube_link"/>
    <origin xyz="${x_tube} ${y_tube2} ${(base_height + tube_height)}"/>
  </joint>

  <joint name="test_tube_3_joint" type="floating">
    <parent link="base"/>
    <child link="test_tube_3_tube_link"/>
    <origin xyz="${x_tube} ${y_tube3} ${(base_height + tube_height)}"/>
  </joint>

</robot>
